import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

function Dashboard() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const token = localStorage.getItem('token');

  // Fetch protected user data when component mounts
  useEffect(() => {
    const fetchUserProfile = async () => {
      if (!token) {
        navigate('/login');
        return;
      }

      try {
      const response = await fetch(`${import.meta.env.VITE_API_URL}/api/auth/me`, {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
            // Send Bearer JWT Token in Authorization header
            Authorization: `Bearer ${token}`,
          },
        });

        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.message || 'Session expired. Please log in again.');
        }

        setUser(data.user);
      } catch (err) {
        setError(err.message);
        // If unauthorized or token error, clear stored session
        localStorage.removeItem('token');
        localStorage.removeItem('user');
        setTimeout(() => {
          navigate('/login');
        }, 1500);
      } finally {
        setLoading(false);
      }
    };

    fetchUserProfile();
  }, [token, navigate]);

  // Logout handler
  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    navigate('/login');
  };

  if (loading) {
    return (
      <div className="main-content">
        <div className="loading-screen">
          <div className="spinner" style={{ width: '36px', height: '36px', borderWidth: '3px' }}></div>
          <p>Verifying JWT and loading protected data...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="main-content">
      <div className="dashboard-container">
        <div className="dashboard-card">
          {/* Header */}
          <div className="dashboard-header">
            <div className="user-welcome">
              <h2>Welcome, {user?.name || 'Explorer'}! 👋</h2>
              <p>You have successfully unlocked the protected dashboard</p>
            </div>
            <div className="status-badge">
              <span className="status-dot"></span>
              JWT Authenticated
            </div>
          </div>

          {/* Error Message if any */}
          {error && (
            <div className="alert alert-error" style={{ marginBottom: '1.5rem' }}>
              <span>⚠️</span>
              <span>{error}</span>
            </div>
          )}

          {/* User Details Grid */}
          <div className="info-grid">
            <div className="info-box">
              <div className="info-label">Full Name</div>
              <div className="info-value">{user?.name || 'N/A'}</div>
            </div>

            <div className="info-box">
              <div className="info-label">Email Address</div>
              <div className="info-value">{user?.email || 'N/A'}</div>
            </div>

            <div className="info-box">
              <div className="info-label">MongoDB User ID</div>
              <div className="info-value" style={{ fontSize: '0.95rem' }}>{user?._id || 'N/A'}</div>
            </div>

            <div className="info-box">
              <div className="info-label">Joined On</div>
              <div className="info-value" style={{ fontSize: '0.95rem' }}>
                {user?.createdAt ? new Date(user.createdAt).toLocaleDateString(undefined, {
                  year: 'numeric',
                  month: 'short',
                  day: 'numeric',
                  hour: '2-digit',
                  minute: '2-digit'
                }) : 'Just now'}
              </div>
            </div>
          </div>

          {/* JWT Token Educational Box */}
          <div className="jwt-section">
            <div className="jwt-title">
              <h4>🔑 Active JSON Web Token (JWT)</h4>
              <span style={{ fontSize: '0.75rem', color: '#94a3b8' }}>Stored in browser localStorage</span>
            </div>
            <p style={{ fontSize: '0.85rem', color: '#94a3b8', marginBottom: '0.6rem' }}>
              This token was generated by your Express backend on login/register and verified by the backend middleware for this page:
            </p>
            <div className="jwt-code-box">
              {token || 'No token found'}
            </div>
          </div>

          {/* Actions */}
          <div className="dashboard-actions">
            <button
              onClick={handleLogout}
              className="btn-danger"
              id="dashboard-logout-btn"
            >
              🚪 Logout
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;
